---

- name: openvpn restart
  service:
    name: "{{openvpn_service_name}}"
    state: restarted

- name: openvpn pack clients
  command: "tar cvzf {{openvpn_keydir}}/{{item.item}}.tar.gz -C {{openvpn_keydir}} {{item.item}}.crt {{item.item}}.key {{item.item}}.ovpn ca.crt"
  when: item.changed
  with_items: openvpn_clients_changed.results

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes